databases:
  - name: private-event
    databaseName: eric
    user: eric

services:
  - type: web
    name: private-event
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: private-event
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
